### ISSUE TITLE
Special/virtual folders - CLSID instead of name - some throwing errors

### ISSUE THREAD

**Issue by youri--** [ThioJoe/ThioJoe-AHK-Scripts#7]
This is an awesome app, thank you for sharing your work!

Using Windows 11 v23H2, I was testing with it and ran into a few issues with special/virtual folders:

1. Trying to switch to the virtual "Home" folder presents a "Home, Catastrophic failure" error message (lol I wouldn't call it catastrophic myself, but OK)
2. Special folders show as their CLSID instead of their friendly name, examples: Home, This PC, WSL root (named "Linux")
3. Can't switch to Windows' Font dir (shell:fonts, usually C:\Windows\Fonts), gives error "Fonts, you don't have permission to open this file"

My testing was done with your program running from "C:\Program Files\ThioJoe" per your suggestion in your YT video.
Version 1.1.0 compiled 11-13-2024.

PS Suggestion for TODO: perhaps you could add an option to the settings dialog to "Start with Windows" (maybe just create a shortcut in shell:startup)?

Thanks again!

**Comment by ThioJoe** [comment]
Hm yea it doesn't seem to work with the "Home" CLSID for some reason. It does work for This PC which is odd. I'll have to look into why. It works if it gets pasted into the top address bar, but to paste into that I would have to have AHK send the hotkey Alt+D instead of using the API which might be less reliable, but might be necessary.

And yea for the CLSIDs I'll have to see about the best way to have it show the friendly name. I'm hoping there's a way to do it via the windows API somehow instead of having to hardcode a list, or parse the registry which could introduce performance issues.

**Comment by ThioJoe** [comment]
Ok the latest v1.2.2 should at least fix the special folders like Home not being navigated to

**Comment by ThioJoe** [comment]
The latest release 1.3.0 should correctly show CLSID names now
